/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Random;
import javax.swing.JOptionPane;
import processamento.Principal;
/**
 *
 * @author Dario
 */
public class TelaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form tela
     */
    public TelaPrincipal() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelFormCliente = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelDados = new javax.swing.JLabel();
        Limpar = new javax.swing.JButton();
        jLabelPrefiixoMZ = new javax.swing.JLabel();
        jLabelProdutos = new javax.swing.JLabel();
        jComboBoxProdutos = new javax.swing.JComboBox<>();
        jLabelQtd = new javax.swing.JLabel();
        jTextFieldQtd = new javax.swing.JTextField();
        jScrollPaneRecibo = new javax.swing.JScrollPane();
        jTextAreaRecibo = new javax.swing.JTextArea();
        jLabelRelatorio = new javax.swing.JLabel();
        jButtonEnviar = new javax.swing.JButton();
        PanelPrincipal = new javax.swing.JPanel();
        jButtonsalvar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BarMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Teclado = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelFormCliente.setBackground(new java.awt.Color(223, 235, 243));
        jPanelFormCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 64, 130));
        jLabelNome.setText("Nome");

        jLabelEndereco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelEndereco.setForeground(new java.awt.Color(0, 64, 130));
        jLabelEndereco.setText("Endereço");

        jLabelNumero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(0, 64, 130));
        jLabelNumero.setText("Telefone");

        jLabelDados.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelDados.setForeground(new java.awt.Color(0, 64, 130));
        jLabelDados.setText("Dados do Cliente");

        Limpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Limpar.setForeground(new java.awt.Color(0, 64, 130));
        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        jLabelPrefiixoMZ.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPrefiixoMZ.setForeground(new java.awt.Color(0, 64, 130));
        jLabelPrefiixoMZ.setText("+258");

        javax.swing.GroupLayout jPanelFormClienteLayout = new javax.swing.GroupLayout(jPanelFormCliente);
        jPanelFormCliente.setLayout(jPanelFormClienteLayout);
        jPanelFormClienteLayout.setHorizontalGroup(
            jPanelFormClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormClienteLayout.createSequentialGroup()
                .addGroup(jPanelFormClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFormClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelFormClienteLayout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(jLabelDados))
                        .addGroup(jPanelFormClienteLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(jPanelFormClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNumero)
                                .addComponent(jLabelEndereco)
                                .addComponent(jLabelNome)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelFormClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelFormClienteLayout.createSequentialGroup()
                            .addComponent(jLabelPrefiixoMZ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelFormClienteLayout.setVerticalGroup(
            jPanelFormClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelDados)
                .addGap(27, 27, 27)
                .addComponent(jLabelNome)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEndereco)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNumero)
                .addGap(18, 18, 18)
                .addGroup(jPanelFormClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabelPrefiixoMZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanelFormCliente);
        jPanelFormCliente.setBounds(20, 80, 300, 430);

        jLabelProdutos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelProdutos.setForeground(java.awt.Color.white);
        jLabelProdutos.setText("Produto");
        getContentPane().add(jLabelProdutos);
        jLabelProdutos.setBounds(350, 80, 60, 15);

        jComboBoxProdutos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBoxProdutos.setForeground(new java.awt.Color(0, 64, 130));
        jComboBoxProdutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cimento", "Ferro Nacional", "Ferro Sul Africano", "Vaso Sanitário", "Autoclismo", "Tinta", "Lava Louça", "Cimento Cola", "Folha de Serra", "Tubo VD", "Tomada Dupla", "Tomada Simples", "Interruptor Duplo", "Interruptor Simples", "Fio 1.5mm", "Fio 2.5mm", "Estribos" }));
        jComboBoxProdutos.setSelectedIndex(-1);
        getContentPane().add(jComboBoxProdutos);
        jComboBoxProdutos.setBounds(350, 110, 190, 40);

        jLabelQtd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelQtd.setForeground(java.awt.Color.white);
        jLabelQtd.setText("Quantidade");
        getContentPane().add(jLabelQtd);
        jLabelQtd.setBounds(350, 170, 90, 15);

        jTextFieldQtd.setForeground(new java.awt.Color(0, 64, 130));
        getContentPane().add(jTextFieldQtd);
        jTextFieldQtd.setBounds(350, 200, 190, 40);

        jTextAreaRecibo.setEditable(false);
        jTextAreaRecibo.setBackground(new java.awt.Color(220, 217, 217));
        jTextAreaRecibo.setColumns(20);
        jTextAreaRecibo.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jTextAreaRecibo.setRows(5);
        jScrollPaneRecibo.setViewportView(jTextAreaRecibo);

        getContentPane().add(jScrollPaneRecibo);
        jScrollPaneRecibo.setBounds(580, 100, 310, 410);

        jLabelRelatorio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelRelatorio.setForeground(java.awt.Color.white);
        jLabelRelatorio.setText("Relatório");
        getContentPane().add(jLabelRelatorio);
        jLabelRelatorio.setBounds(580, 70, 70, 19);

        jButtonEnviar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEnviar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEnviar.setForeground(new java.awt.Color(0, 64, 130));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar);
        jButtonEnviar.setBounds(340, 479, 90, 30);

        PanelPrincipal.setBackground(new java.awt.Color(0, 64, 130));
        PanelPrincipal.setLayout(null);

        jButtonsalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonsalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonsalvar.setForeground(new java.awt.Color(0, 64, 130));
        jButtonsalvar.setText("Guardar");
        jButtonsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalvarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(jButtonsalvar);
        jButtonsalvar.setBounds(476, 467, 100, 30);

        jButtonImprimir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonImprimir.setForeground(new java.awt.Color(0, 64, 130));
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        PanelPrincipal.add(jButtonImprimir);
        jButtonImprimir.setBounds(476, 508, 100, 30);

        Sair.setBackground(new java.awt.Color(255, 51, 51));
        Sair.setForeground(java.awt.Color.white);
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        PanelPrincipal.add(Sair);
        Sair.setBounds(823, 30, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img-img.png"))); // NOI18N
        PanelPrincipal.add(jLabel2);
        jLabel2.setBounds(30, 30, 120, 80);

        getContentPane().add(PanelPrincipal);
        PanelPrincipal.setBounds(-10, -30, 930, 570);

        BarMenu.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        Teclado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        Teclado.setText("Limpar Campos");
        Teclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TecladoActionPerformed(evt);
            }
        });
        jMenu1.add(Teclado);

        BarMenu.add(jMenu1);

        setJMenuBar(BarMenu);

        setSize(new java.awt.Dimension(913, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   private String nome;
    private String endereco;
    private String telefone;
    private String relato;
    private int qtd;
    private double preco;
    private int produtos;
    private double valor;
    
    Principal process = new Principal(this);

    public double getValor() {
        return valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public int getProdutos() {
        return produtos;
    }

    public void setProdutos(int produtos) {
        this.produtos = produtos;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEndereco() {
        return endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    public String getTelefone() {
        return telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public int getQtd() {
        return qtd;
    }

    public void setQtd(int qtd) {
        this.qtd = qtd;
    }

    public double getPreco() {
        return preco;
    }

    public void setPreco(double preco) {
        this.preco = preco;
    }

    public String getRelato() {
        return relato;
    }

    public void setRelato(String relato) {
        this.relato = relato;
    }


    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // Botao Guardar
        setNome(jTextFieldNome.getText());
        setEndereco(jTextFieldEndereco.getText());
        setTelefone(jTextFieldNumero.getText());
        setProdutos(jComboBoxProdutos.getSelectedIndex());
        
        try {
            setQtd(Integer.parseInt(jTextFieldQtd.getText()));
        } catch (NumberFormatException e) {
            process.QtdErro();
        }

        process.Precario(getProdutos(), getPreco(), getQtd(), getValor());

        Random r = new Random();
        int c = r.nextInt(99);

        String nrRelatorio = String.valueOf(c);
        LocalDate data = LocalDate.now();
        LocalTime horas = LocalTime.now();
        
        if(getNome().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo do nome nao pode estar vazio!");
        } else if(getEndereco().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo do endereco nao pode estar vazio!");
        } else if (getTelefone().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo do telefone nao pode estar vazio!");
        }

        jTextAreaRecibo.setText(
                "Relatorio N* : " + nrRelatorio
                + "\n" + "Nome : " + getNome()
                + "\n" + "Endereco :" + getEndereco()
                + "\n" + "Contacto (+258) :" + getTelefone()
                + "\n" + "Produto :" + jComboBoxProdutos.getSelectedItem()
                + "\n" + "Quantidade :" + getQtd() + " Units"
                + "\n" + "Preco :" + process.getPreco() + " MTs"
                + "\n" + "Data : " + data
                + "\n" + "Horas : " + horas
        );

        process.Enviar(getNome(), getTelefone(), getEndereco());

        
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalvarActionPerformed
        // Botao guardar(salvar)
        setRelato(jTextAreaRecibo.getText());
        process.SaveRelato(getRelato());
    }//GEN-LAST:event_jButtonsalvarActionPerformed
    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        //Botao imprimir
        process.criar();
        process.escrever();
        process.Imprimir("D:\\Sistema\\Ferragem\\Relatorios\\Relatorio.doc");
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // Botao Limpar
        jTextFieldNome.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNumero.setText("");
        jTextAreaRecibo.setText("");
        jTextFieldQtd.setText("");
        jComboBoxProdutos.setSelectedIndex(-1);
     
       
    }//GEN-LAST:event_LimparActionPerformed

    private void TecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TecladoActionPerformed
        jTextFieldNome.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNumero.setText("");
        jTextAreaRecibo.setText("");
        jTextFieldQtd.setText("");
        jComboBoxProdutos.setSelectedIndex(-1);
    }//GEN-LAST:event_TecladoActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // Botao Sair
        process.Sair();

    }//GEN-LAST:event_SairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarMenu;
    private javax.swing.JButton Limpar;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton Sair;
    private javax.swing.JMenuItem Teclado;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonsalvar;
    private javax.swing.JComboBox<String> jComboBoxProdutos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDados;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPrefiixoMZ;
    private javax.swing.JLabel jLabelProdutos;
    private javax.swing.JLabel jLabelQtd;
    private javax.swing.JLabel jLabelRelatorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelFormCliente;
    private javax.swing.JScrollPane jScrollPaneRecibo;
    private javax.swing.JTextArea jTextAreaRecibo;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldQtd;
    // End of variables declaration//GEN-END:variables
}
